server:
  port: 6003

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**  
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**


eureka:
  client:
    register-with-eureka: true
    feth-registry: true
    service-url:
      defaultZone: http://localhost:6001/eureka
    instance:
      hostname: localhost
